name: Deploy Streamlit to Cloud Run

on:
  push:
    branches:
      - main
      - devops
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true
        type: choice
        options:
          - devops

env:
  PROJECT_ID: gcp-new-project-506608
  REGION: europe-west1
  SERVICE_NAME: streamlit-app
  ARTIFACT_REPO: streamlit-repo
  IMAGE_NAME: streamlit-app
  BACKEND_JOB_NAME: streamlit-app-backend
  BACKEND_DOCKERFILE: ./src/backend/Dockerfile
  FRONTEND_SERVICE_NAME: streamlit-app-frontend
  FRONTEND_DOCKERFILE: ./src/frontend/Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:

      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/173230660638/locations/global/workloadIdentityPools/github-access/providers/github-access'
          service_account: 'github-access@gcp-new-project-506608.iam.gserviceaccount.com'

      # 3. Check GCP identity
      - name: Check GCP identity
        run: |
          gcloud auth list
          gcloud config get-value project

      # 4. Setup gcloud
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      # 5. Create repository if it doesn't exist
      - name: Create Artifact Registry repository if not exists
        run: |
          if gcloud artifacts repositories describe "${{ env.ARTIFACT_REPO }}" \
            --location="${{ env.REGION }}" \
            --project="${{ env.PROJECT_ID }}" > /dev/null 2>&1; then
            echo "Artifact Registry repository already exists."
          else
            echo "Creating Artifact Registry repository..."
            gcloud artifacts repositories create "${{ env.ARTIFACT_REPO }}" \
              --repository-format=docker \
              --location="${{ env.REGION }}" \
              --project="${{ env.PROJECT_ID }}" \
              --description="Docker repository for Streamlit application"
          fi

      # 6. Configure Docker
      - name: Configure Docker
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      # 7. Build backend image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.BACKEND_JOB_NAME }}:${{ github.sha }} \
            ./src/backend

      # 8. Push backend image to Artifact Registry
      - name: Push backend image
        run: |
          docker push \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.BACKEND_JOB_NAME }}:${{ github.sha }}

      # 9. Deploy backend to Cloud Run Job      
      # - name: Deploy backend to Cloud Run Job
      #   run: |
      #     # Check if the job already exists to decide whether to update or create
      #     if gcloud run jobs describe ${{ env.BACKEND_JOB_NAME }} --region ${{ env.REGION }} &>/dev/null; then
      #       gcloud run jobs update ${{ env.BACKEND_JOB_NAME }} \
      #         --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.BACKEND_JOB_NAME }}:${{ github.sha }} \
      #         --region ${{ env.REGION }}
      #     else
      #       gcloud run jobs create ${{ env.BACKEND_JOB_NAME }} \
      #         --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.BACKEND_JOB_NAME }}:${{ github.sha }} \
      #         --region ${{ env.REGION }}
      #     fi

      # 9. Deploy backend to Cloud Run service
      - name: Deploy backend to Cloud Run service
        run: |
          gcloud run deploy ${{ env.BACKEND_JOB_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.BACKEND_JOB_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated
            
      #  10. Build frontend image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.FRONTEND_SERVICE_NAME }}:${{ github.sha }} \
            ./src/frontend

      # 11. Push frontend image to Artifact Registry
      - name: Push frontend image
        run: |
          docker push \
            ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.FRONTEND_SERVICE_NAME }}:${{ github.sha }}

      # 12. Deploy frontend to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.FRONTEND_SERVICE_NAME }} \
            --image ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.FRONTEND_SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated